[book]
title = "steam-config-nix"
description = "Declaratively manage Steam and your apps on NixOS or Home Manager"
authors = ["different-name"]
language = "en"
src = "src"

[output.html]
default-theme = "latte"
preferred-dark-theme = "mocha"
additional-css = ["theme/catppuccin.css", "theme/custom.css"]
git-repository-url = "https://github.com/different-name/steam-config-nix"
edit-url-template = "https://github.com/different-name/steam-config-nix/edit/master/docs/{path}"

[output.html.playground]
runnable = false
