title = "steam-config-nix"
theme = "hextra"
enableRobotsTXT = true

[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[params.navbar]
displayTitle = true
displayLogo = false

[params.footer]
enable = true
displayCopyright = false
displayPoweredBy = false

[params.editURL]
enable = true
base = "https://github.com/different-name/steam-config-nix/edit/main/docs/content"

[params.theme]
default = "system"
displayToggle = true

[[menu.main]]
name = "Guide"
pageRef = "/docs"
weight = 1

[[menu.main]]
name = "Options"
url = "/search/"
weight = 2

[[menu.main]]
name = "Search"
weight = 3
[menu.main.params]
type = "search"

[[menu.main]]
name = "GitHub"
url = "https://github.com/different-name/steam-config-nix"
weight = 4
[menu.main.params]
icon = "github"

[params.search]
enable = true
type = "flexsearch"

[params.search.flexsearch]
js = "js/flexsearch.bundle.min.js"
index = "content"
