[project]
name = "steam-config-patcher"
version = "0.6.0"
description = "Patch Steam vdf files using JSON input"
authors = [{ name = "different-name", email = "hello@different-name.dev" }]
dependencies = ["pydantic", "psutil", "pillow"]
requires-python = ">=3.13"
license = "GPL-3.0-or-later"

[project.scripts]
steam-config-patcher = "steam_config_patcher.main:main"

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = ["pytest", "mypy", "types-psutil"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.mypy]
python_version = "3.13"
plugins = ["pydantic.mypy"]
warn_unused_ignores = true
warn_redundant_casts = true
